appConfig:
  appId: ""
  appVersion: 1.0.0
  buildId: 7a150e43586848cebb00c09cf839b0f2
  connectors: TIBCO Flogo Connector for General
  customFQImage: ""
  flogoBaseImageTag: 2.26.1-b392
  flogoBuildTypeTag: 2.26.1-b392
  lastUpdated: "1782364427"
  originalAppName: HelloFDA
  tags: ""
appInit:
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: true
appProps: {}
appSecrets: {}
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
engineProps:
  FLOGO_LOG_LEVEL: ERROR
  FLOGO_OTEL_TRACE: "false"
engineSecrets: {}
executionHistory:
  enabled: false
flogoapp:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: false
fluentBit:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      - CAP_NET_RAW
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
fullnameOverride: hellofda
image:
  appInitImageTag: "72"
  fluentBitImageTag: 5.0.6
  repository: csgprduswrepoedge.jfrog.io/tibco-platform-docker-prod/
imagePullSecrets:
- name: ctmes5qkjuonrdun3s8g
networkPolicy:
  databaseEgress: enable
  internetAll: enable
  internetWeb: enable
  msgInfra: enable
  proxyEgress: enable
  userApps: enable
replicaCount: 0
service:
  ports: []
  serviceDescription: ""
serviceMesh:
  enabled: false
